<?php

/**
 * @file
 * Contains react.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function react_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the react module.
    case 'help.page.react':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('React api') . '</p>';
      return $output;

    default:
  }
}
